export default {
  selectedTags: [
    {
      id: '23',
      title: 'Front End',
    },
    {
      id: '25',
      title: 'Functional Programming',
    },
  ],
  invalid: false,
  fields: {
    titleInput: {
      name: 'titleInput',
      value: 'Lessons Learned From Functional Reactive Programming',
      initialValue: '',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: true,
      visited: true,
      autofilled: false,
    },
    bodyInput: {
      name: 'bodyInput',
      value: 'some value',
      initialValue: '',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    tagsInput: {
      name: 'tagsInput',
      value: '',
      initialValue: '',
      valid: true,
      invalid: false,
      dirty: false,
      pristine: true,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    featureImageInput: {
      name: 'featureImageInput',
      value: 'http://res.cloudinary.com/dc1qjoyvn/image/upload/v1468092213/efjetjkyzb6b9tcxrxqp.png',
      initialValue: '',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
  },
  pastTags: [
    {
      id: '23',
      title: 'Front End',
    },
    {
      id: '25',
      title: 'Functional Programming',
    },
    {
      id: '1',
      title: 'React',
    },
    {
      id: '24',
      title: 'Immutable Architecture',
    },
    {
      id: '22',
      title: 'Performance',
    },
  ],
};
