// flow-typed signature: dc752ce27c5e265882798d87106276a8
// flow-typed version: <<STUB>>/assemble_v^0.3.83/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'assemble'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'assemble' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'assemble/Gruntfile' {
  declare module.exports: any;
}

declare module 'assemble/lib/assemble' {
  declare module.exports: any;
}

declare module 'assemble/lib/data/index' {
  declare module.exports: any;
}

declare module 'assemble/lib/data/markdown' {
  declare module.exports: any;
}

declare module 'assemble/lib/data/yfm' {
  declare module.exports: any;
}

declare module 'assemble/lib/engine/helpers' {
  declare module.exports: any;
}

declare module 'assemble/lib/engine/index' {
  declare module.exports: any;
}

declare module 'assemble/lib/util/collection' {
  declare module.exports: any;
}

declare module 'assemble/lib/util/index' {
  declare module.exports: any;
}

declare module 'assemble/tasks/assemble' {
  declare module.exports: any;
}

declare module 'assemble/tasks/subgrunt' {
  declare module.exports: any;
}

declare module 'assemble/test/assemble_test' {
  declare module.exports: any;
}

declare module 'assemble/test/engine_test' {
  declare module.exports: any;
}

declare module 'assemble/test/helpers/helpers-with-register' {
  declare module.exports: any;
}

declare module 'assemble/test/helpers/helpers' {
  declare module.exports: any;
}

declare module 'assemble/test/markdown_test' {
  declare module.exports: any;
}

declare module 'assemble/test/yfm_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'assemble/Gruntfile.js' {
  declare module.exports: $Exports<'assemble/Gruntfile'>;
}
declare module 'assemble/lib/assemble.js' {
  declare module.exports: $Exports<'assemble/lib/assemble'>;
}
declare module 'assemble/lib/data/index.js' {
  declare module.exports: $Exports<'assemble/lib/data/index'>;
}
declare module 'assemble/lib/data/markdown.js' {
  declare module.exports: $Exports<'assemble/lib/data/markdown'>;
}
declare module 'assemble/lib/data/yfm.js' {
  declare module.exports: $Exports<'assemble/lib/data/yfm'>;
}
declare module 'assemble/lib/engine/helpers.js' {
  declare module.exports: $Exports<'assemble/lib/engine/helpers'>;
}
declare module 'assemble/lib/engine/index.js' {
  declare module.exports: $Exports<'assemble/lib/engine/index'>;
}
declare module 'assemble/lib/util/collection.js' {
  declare module.exports: $Exports<'assemble/lib/util/collection'>;
}
declare module 'assemble/lib/util/index.js' {
  declare module.exports: $Exports<'assemble/lib/util/index'>;
}
declare module 'assemble/tasks/assemble.js' {
  declare module.exports: $Exports<'assemble/tasks/assemble'>;
}
declare module 'assemble/tasks/subgrunt.js' {
  declare module.exports: $Exports<'assemble/tasks/subgrunt'>;
}
declare module 'assemble/test/assemble_test.js' {
  declare module.exports: $Exports<'assemble/test/assemble_test'>;
}
declare module 'assemble/test/engine_test.js' {
  declare module.exports: $Exports<'assemble/test/engine_test'>;
}
declare module 'assemble/test/helpers/helpers-with-register.js' {
  declare module.exports: $Exports<'assemble/test/helpers/helpers-with-register'>;
}
declare module 'assemble/test/helpers/helpers.js' {
  declare module.exports: $Exports<'assemble/test/helpers/helpers'>;
}
declare module 'assemble/test/markdown_test.js' {
  declare module.exports: $Exports<'assemble/test/markdown_test'>;
}
declare module 'assemble/test/yfm_test.js' {
  declare module.exports: $Exports<'assemble/test/yfm_test'>;
}
