// flow-typed signature: c31111ab834c5f508caf10a1febd6e51
// flow-typed version: <<STUB>>/lru-memoize_v^1.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lru-memoize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lru-memoize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lru-memoize/dist/lru-memoize' {
  declare module.exports: any;
}

declare module 'lru-memoize/dist/lru-memoize.min' {
  declare module.exports: any;
}

declare module 'lru-memoize/lib/deepEquals' {
  declare module.exports: any;
}

declare module 'lru-memoize/lib/index' {
  declare module.exports: any;
}

declare module 'lru-memoize/lib/lruCache' {
  declare module.exports: any;
}

declare module 'lru-memoize/lib/memoize' {
  declare module.exports: any;
}

declare module 'lru-memoize/lib/singletonCache' {
  declare module.exports: any;
}

declare module 'lru-memoize/webpack.config.base' {
  declare module.exports: any;
}

declare module 'lru-memoize/webpack.config.development' {
  declare module.exports: any;
}

declare module 'lru-memoize/webpack.config.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lru-memoize/dist/lru-memoize.js' {
  declare module.exports: $Exports<'lru-memoize/dist/lru-memoize'>;
}
declare module 'lru-memoize/dist/lru-memoize.min.js' {
  declare module.exports: $Exports<'lru-memoize/dist/lru-memoize.min'>;
}
declare module 'lru-memoize/lib/deepEquals.js' {
  declare module.exports: $Exports<'lru-memoize/lib/deepEquals'>;
}
declare module 'lru-memoize/lib/index.js' {
  declare module.exports: $Exports<'lru-memoize/lib/index'>;
}
declare module 'lru-memoize/lib/lruCache.js' {
  declare module.exports: $Exports<'lru-memoize/lib/lruCache'>;
}
declare module 'lru-memoize/lib/memoize.js' {
  declare module.exports: $Exports<'lru-memoize/lib/memoize'>;
}
declare module 'lru-memoize/lib/singletonCache.js' {
  declare module.exports: $Exports<'lru-memoize/lib/singletonCache'>;
}
declare module 'lru-memoize/webpack.config.base.js' {
  declare module.exports: $Exports<'lru-memoize/webpack.config.base'>;
}
declare module 'lru-memoize/webpack.config.development.js' {
  declare module.exports: $Exports<'lru-memoize/webpack.config.development'>;
}
declare module 'lru-memoize/webpack.config.production.js' {
  declare module.exports: $Exports<'lru-memoize/webpack.config.production'>;
}
