// flow-typed signature: 3f08f9f5372d2253a2e759cf3b438f04
// flow-typed version: <<STUB>>/react-css-stagger_v0.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-css-stagger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-css-stagger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-css-stagger/dist/index' {
  declare module.exports: any;
}

declare module 'react-css-stagger/src/index' {
  declare module.exports: any;
}

declare module 'react-css-stagger/src/Stagger' {
  declare module.exports: any;
}

declare module 'react-css-stagger/src/StaggerSpec' {
  declare module.exports: any;
}

declare module 'react-css-stagger/tests.bundle' {
  declare module.exports: any;
}

declare module 'react-css-stagger/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-css-stagger/dist/index.js' {
  declare module.exports: $Exports<'react-css-stagger/dist/index'>;
}
declare module 'react-css-stagger/src/index.js' {
  declare module.exports: $Exports<'react-css-stagger/src/index'>;
}
declare module 'react-css-stagger/src/Stagger.js' {
  declare module.exports: $Exports<'react-css-stagger/src/Stagger'>;
}
declare module 'react-css-stagger/src/StaggerSpec.js' {
  declare module.exports: $Exports<'react-css-stagger/src/StaggerSpec'>;
}
declare module 'react-css-stagger/tests.bundle.js' {
  declare module.exports: $Exports<'react-css-stagger/tests.bundle'>;
}
declare module 'react-css-stagger/webpack.config.js' {
  declare module.exports: $Exports<'react-css-stagger/webpack.config'>;
}
