// flow-typed signature: 24cfcad3776d9f9e2d9a889f8e2c246b
// flow-typed version: <<STUB>>/react-md-editor_v^0.2.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-md-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-md-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-md-editor/dist/react-md-editor' {
  declare module.exports: any;
}

declare module 'react-md-editor/dist/react-md-editor.min' {
  declare module.exports: any;
}

declare module 'react-md-editor/example/src/example' {
  declare module.exports: any;
}

declare module 'react-md-editor/gulpfile' {
  declare module.exports: any;
}

declare module 'react-md-editor/lib/format' {
  declare module.exports: any;
}

declare module 'react-md-editor/lib/icons/bold' {
  declare module.exports: any;
}

declare module 'react-md-editor/lib/icons/index' {
  declare module.exports: any;
}

declare module 'react-md-editor/lib/icons/italic' {
  declare module.exports: any;
}

declare module 'react-md-editor/lib/icons/link' {
  declare module.exports: any;
}

declare module 'react-md-editor/lib/icons/oList' {
  declare module.exports: any;
}

declare module 'react-md-editor/lib/icons/quote' {
  declare module.exports: any;
}

declare module 'react-md-editor/lib/icons/uList' {
  declare module.exports: any;
}

declare module 'react-md-editor/lib/MDEditor' {
  declare module.exports: any;
}

declare module 'react-md-editor/src/format' {
  declare module.exports: any;
}

declare module 'react-md-editor/src/icons/bold' {
  declare module.exports: any;
}

declare module 'react-md-editor/src/icons/index' {
  declare module.exports: any;
}

declare module 'react-md-editor/src/icons/italic' {
  declare module.exports: any;
}

declare module 'react-md-editor/src/icons/link' {
  declare module.exports: any;
}

declare module 'react-md-editor/src/icons/oList' {
  declare module.exports: any;
}

declare module 'react-md-editor/src/icons/quote' {
  declare module.exports: any;
}

declare module 'react-md-editor/src/icons/uList' {
  declare module.exports: any;
}

declare module 'react-md-editor/src/MDEditor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-md-editor/dist/react-md-editor.js' {
  declare module.exports: $Exports<'react-md-editor/dist/react-md-editor'>;
}
declare module 'react-md-editor/dist/react-md-editor.min.js' {
  declare module.exports: $Exports<'react-md-editor/dist/react-md-editor.min'>;
}
declare module 'react-md-editor/example/src/example.js' {
  declare module.exports: $Exports<'react-md-editor/example/src/example'>;
}
declare module 'react-md-editor/gulpfile.js' {
  declare module.exports: $Exports<'react-md-editor/gulpfile'>;
}
declare module 'react-md-editor/lib/format.js' {
  declare module.exports: $Exports<'react-md-editor/lib/format'>;
}
declare module 'react-md-editor/lib/icons/bold.js' {
  declare module.exports: $Exports<'react-md-editor/lib/icons/bold'>;
}
declare module 'react-md-editor/lib/icons/index.js' {
  declare module.exports: $Exports<'react-md-editor/lib/icons/index'>;
}
declare module 'react-md-editor/lib/icons/italic.js' {
  declare module.exports: $Exports<'react-md-editor/lib/icons/italic'>;
}
declare module 'react-md-editor/lib/icons/link.js' {
  declare module.exports: $Exports<'react-md-editor/lib/icons/link'>;
}
declare module 'react-md-editor/lib/icons/oList.js' {
  declare module.exports: $Exports<'react-md-editor/lib/icons/oList'>;
}
declare module 'react-md-editor/lib/icons/quote.js' {
  declare module.exports: $Exports<'react-md-editor/lib/icons/quote'>;
}
declare module 'react-md-editor/lib/icons/uList.js' {
  declare module.exports: $Exports<'react-md-editor/lib/icons/uList'>;
}
declare module 'react-md-editor/lib/MDEditor.js' {
  declare module.exports: $Exports<'react-md-editor/lib/MDEditor'>;
}
declare module 'react-md-editor/src/format.js' {
  declare module.exports: $Exports<'react-md-editor/src/format'>;
}
declare module 'react-md-editor/src/icons/bold.js' {
  declare module.exports: $Exports<'react-md-editor/src/icons/bold'>;
}
declare module 'react-md-editor/src/icons/index.js' {
  declare module.exports: $Exports<'react-md-editor/src/icons/index'>;
}
declare module 'react-md-editor/src/icons/italic.js' {
  declare module.exports: $Exports<'react-md-editor/src/icons/italic'>;
}
declare module 'react-md-editor/src/icons/link.js' {
  declare module.exports: $Exports<'react-md-editor/src/icons/link'>;
}
declare module 'react-md-editor/src/icons/oList.js' {
  declare module.exports: $Exports<'react-md-editor/src/icons/oList'>;
}
declare module 'react-md-editor/src/icons/quote.js' {
  declare module.exports: $Exports<'react-md-editor/src/icons/quote'>;
}
declare module 'react-md-editor/src/icons/uList.js' {
  declare module.exports: $Exports<'react-md-editor/src/icons/uList'>;
}
declare module 'react-md-editor/src/MDEditor.js' {
  declare module.exports: $Exports<'react-md-editor/src/MDEditor'>;
}
