// flow-typed signature: 7cf5a470724bf50c797e68f1f9a090a6
// flow-typed version: <<STUB>>/selectors_v0.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'selectors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'selectors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'selectors/examples/simple' {
  declare module.exports: any;
}

declare module 'selectors/lib/args-to-arr' {
  declare module.exports: any;
}

declare module 'selectors/lib/just-curry' {
  declare module.exports: any;
}

declare module 'selectors/lib/just-curryn' {
  declare module.exports: any;
}

declare module 'selectors/selectors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'selectors/examples/simple.js' {
  declare module.exports: $Exports<'selectors/examples/simple'>;
}
declare module 'selectors/lib/args-to-arr.js' {
  declare module.exports: $Exports<'selectors/lib/args-to-arr'>;
}
declare module 'selectors/lib/just-curry.js' {
  declare module.exports: $Exports<'selectors/lib/just-curry'>;
}
declare module 'selectors/lib/just-curryn.js' {
  declare module.exports: $Exports<'selectors/lib/just-curryn'>;
}
declare module 'selectors/selectors.js' {
  declare module.exports: $Exports<'selectors/selectors'>;
}
