// flow-typed signature: 3f0bd0243284c0f3ec86027aa18ccea8
// flow-typed version: <<STUB>>/strip-markdown_v^2.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strip-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'strip-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'strip-markdown/index' {
  declare module.exports: $Exports<'strip-markdown'>;
}
declare module 'strip-markdown/index.js' {
  declare module.exports: $Exports<'strip-markdown'>;
}
