export const CREATE_POST_SET_SELECTED_TAGS = 'CREATE_POST_SET_SELECTED_TAGS';
export const CREATE_POST_SET_ERROR = 'CREATE_POST_SET_ERROR';
export const CREATE_POST_SET_MESSAGE = 'CREATE_POST_SET_MESSAGE';
export const CREATE_POST_CLEAR_ERROR = 'CREATE_POST_CLEAR_ERROR';
export const CREATE_POST_CLEAR_MESSAGE = 'CREATE_POST_CLEAR_MESSAGE';
