export default {
  invalid: false,
  fields: {
    titleInput: {
      name: 'titleInput',
      value: 'Udacity Alumni API',
      initialValue: 'Udacity Alumni API',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    descriptionInput: {
      name: 'descriptionInput',
      value: 'The Udacity Alumni Development team is building a bespoke publishing platform and social network for the alumni community.  We built a custom GraphQL powered backend API and micro-services for the purposes of serving dynamic data and providing authentication for the front end.',
      initialValue: 'The Udacity Alumni Development team is building a bespoke publishing platform and social network for the alumni community.  We built a custom GraphQL powered backend API and micro-services for the purposes of serving dynamic data and providing authentication for the front end.',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    captionInput: {
      name: 'captionInput',
      value: 'Custom GraphQL on Rails API and Micro-services',
      initialValue: 'Custom GraphQL on Rails API and Micro-services',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    repoUrlInput: {
      name: 'repoUrlInput',
      value: 'https://github.com/udacityalumni/alumni-api',
      initialValue: 'https://github.com/udacityalumni/alumni-api',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    projectUrlInput: {
      name: 'projectUrlInput',
      value: '',
      initialValue: '',
      valid: true,
      invalid: false,
      dirty: false,
      pristine: true,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    categoryInput: {
      name: 'categoryInput',
      value: 'Backend',
      initialValue: 'Backend',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    milestonesInput: {
      name: 'milestonesInput',
      value: '- Built a GraphQL on Rails API to allow for declarative query collocation \n - As team leader, lead the engineering of the Udacity Alumni Web application, with over 800 commits from 20+ engineers from around the world \n  - Optimized the data-loading functionality using server optimization techniques',
      initialValue: '- Built a GraphQL on Rails API to allow for declarative query collocation \n - As team leader, lead the engineering of the Udacity Alumni Web application, with over 800 commits from 20+ engineers from around the world \n  - Optimized the data-loading functionality using server optimization techniques',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    technicalReviewInput: {
      name: 'technicalReviewInput',
      value: null,
      initialValue: null,
      valid: true,
      invalid: false,
      dirty: false,
      pristine: true,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    reviewerNameInput: {
      name: 'reviewerNameInput',
      value: null,
      initialValue: null,
      valid: true,
      invalid: false,
      dirty: false,
      pristine: true,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    technicalInformationInput: {
      name: 'technicalInformationInput',
      value: 'Built a custom GraphQL back end running on Ruby on Rails.',
      initialValue: 'Built a custom GraphQL back end running on Ruby on Rails.',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    designPatternsInput: {
      name: 'designPatternsInput',
      value: 'Followed the micro-service architecture, serving data via a single endpoint with GraphQL, allowing for declarative collocated queries and performant network requests.',
      initialValue: 'Followed the micro-service architecture, serving data via a single endpoint with GraphQL, allowing for declarative collocated queries and performant network requests.',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
    featureImageInput: {
      name: 'featureImageInput',
      value: 'https://github.com/RyanCCollins/cdn/blob/master/portfolio-image-gallery-images/udacity-api.png?raw=true',
      initialValue: 'https://github.com/RyanCCollins/cdn/blob/master/portfolio-image-gallery-images/udacity-api.png?raw=true',
      valid: true,
      invalid: false,
      dirty: true,
      pristine: false,
      active: false,
      touched: false,
      visited: false,
      autofilled: false,
    },
  },
  pastTags: [
    {
      id: '10',
      title: 'Node',
    },
    {
      id: '17',
      title: 'Swift',
    },
    {
      id: '4',
      title: 'Flux',
    },
    {
      id: '5',
      title: 'ES6',
    },
    {
      id: '6',
      title: 'Bootstrap',
    },
    {
      id: '16',
      title: 'Model View Controller',
    },
    {
      id: '1',
      title: 'React',
    },
    {
      id: '19',
      title: 'Model View Presenter',
    },
    {
      id: '11',
      title: 'Python',
    },
    {
      id: '2',
      title: 'GraphQL',
    },
    {
      id: '9',
      title: 'Ruby on Rails',
    },
    {
      id: '13',
      title: 'Sass',
    },
    {
      id: '18',
      title: 'Core Data',
    },
    {
      id: '21',
      title: 'Axios',
    },
    {
      id: '7',
      title: 'Grommet',
    },
    {
      id: '20',
      title: 'REST',
    },
    {
      id: '12',
      title: 'Material UI',
    },
    {
      id: '8',
      title: 'Apollo',
    },
    {
      id: '14',
      title: 'Foundation',
    },
    {
      id: '15',
      title: 'Docker',
    },
    {
      id: '3',
      title: 'Redux',
    },
  ],
  initialTags: [
    {
      title: 'GraphQL',
    },
    {
      title: 'Apollo',
    },
    {
      title: 'Ruby on Rails',
    },
  ],
};
