export const LANDING_SHOW_IMAGE = 'LANDING_SHOW_IMAGE';
export const LANDING_SHOW_HEADLINE = 'LANDING_SHOW_HEADLINE';
export const LANDING_SHOW_BUTTON = 'LANDING_SHOW_BUTTON';

export const LOAD_GIT_DATA_INITIATION = 'LOAD_GIT_DATA_INITIATION';
export const LOAD_GIT_DATA_SUCCESS = 'LOAD_GIT_DATA_SUCCESS';
export const LOAD_GIT_DATA_FAILURE = 'LOAD_GIT_DATA_FAILURE';
export const CLEAR_LANDING_ERROR = 'CLEAR_LANDING_ERROR';

export const TOGGLE_LANDING_LOGO_HOVERED = 'TOGGLE_LANDING_LOGO_HOVERED';
