export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';
export const CREATE_PROJECT_MESSAGE = 'CREATE_PROJECT_MESSAGE';
export const CLEAR_CREATE_PROJECT_ERROR = 'CLEAR_CREATE_PROJECT_ERROR';
export const CLEAR_CREATE_PROJECT_MESSAGE = 'CLEAR_CREATE_PROJECT_MESSAGE';
export const CREATE_PROJECT_ADD_TAG = 'CREATE_PROJECT_ADD_TAG';
