export const ON_EDIT_PROJECT_COMMENT = 'ON_EDIT_PROJECT_COMMENT';
export const PROJECT_MESSAGE = 'PROJECT_MESSAGE';
export const PROJECT_ERROR = 'PROJECT_ERROR';
export const PROJECT_CLEAR_TOAST = 'PROJECT_CLEAR_TOAST';
