export const ON_EDIT_COMMENT = 'ON_EDIT_COMMENT';
export const TUTORIAL_MESSAGE = 'TUTORIAL_MESSAGE';
export const TUTORIAL_ERROR = 'TUTORIAL_ERROR';
export const TUTORIAL_CLEAR_TOAST = 'TUTORIAL_CLEAR_TOAST';
