export const FEEDBACK_SUBMISSION_INITIATION = 'FEEDBACK_SUBMISSION_INITIATION';
export const FEEDBACK_SUBMISSION_ERROR = 'FEEDBACK_SUBMISSION_ERROR';
export const FEEDBACK_SUBMISSION_MESSAGE = 'FEEDBACK_SUBMISSION_MESSAGE';
export const TOGGLE_FEEDBACK_MODAL = 'TOGGLE_FEEDBACK_MODAL';
export const FEEDBACK_CLEAR_ALERTS = 'FEEDBACK_CLEAR_ALERTS';
