export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const INVALIDATE_USER = 'INVALIDATE_USER';
export const APP_SET_MOBILE = 'APP_SET_MOBILE';
export const APP_ON_TOGGLE_NAV = 'APP_ON_TOGGLE_NAV';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const CLEAR_SEARCH_TERM = 'CLEAR_SEARCH_TERM';
export const APP_DOCK_NAVIGATION = 'APP_DOCK_NAVIGATION';
export const APP_UNDOCK_NAVIGATION = 'APP_UNDOCK_NAVIGATION';
