export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const INVALIDATE_USER = 'INVALIDATE_USER';
export const APP_SET_MOBILE = 'APP_SET_MOBILE';
export const APP_ON_TOGGLE_NAV = 'APP_ON_TOGGLE_NAV';
