export const CONTACT_INITIATE_LOADING = 'CONTACT_INITIATE_LOADING';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_ERROR = 'CONTACT_ERROR';
export const CONTACT_CLEAR_ERROR = 'CONTACT_CLEAR_ERROR';
export const CONTACT_CLEAR_MESSAGE = 'CONTACT_CLEAR_MESSAGE';
