export default {
  nameInput: {
    name: 'nameInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'Value Required',
    active: false,
    touched: true,
    visited: true,
    autofilled: false,
  },
  emailInput: {
    name: 'emailInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'Value Required',
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  categoryInput: {
    name: 'categoryInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'Value Required',
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  messageInput: {
    name: 'messageInput',
    value: '',
    initialValue: '',
    valid: false,
    invalid: true,
    dirty: false,
    pristine: true,
    error: 'Value Required',
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
  categories: [
    'job',
    'tutorial',
    'suggestion',
    'other',
  ],
  invalid: true,
};
