export const PORTFOLIO_SET_PROJECTS = 'PORTFOLIO_SET_PROJECTS';
export const PORTFOLIO_SET_CURRENT_PAGE = 'PORTFOLIO_SET_CURRENT_PAGE';
export const PORTFOLIO_SET_SEARCH_TERM = 'PORTFOLIO_SET_SEARCH_TERM';
export const PORTFOLIO_SET_TAGS = 'PORTFOLIO_SET_TAGS';
export const PORTFOLIO_APPLY_FILTERS = 'PORTFOLIO_APPLY_FILTERS';
export const PORTFOLIO_TOGGLE_MODAL = 'PORTFOLIO_TOGGLE_MODAL';
export const PORTFOLIO_CLEAR_FILTERS = 'PORTFOLIO_CLEAR_FILTERS';
